server {
    listen 80;
    server_name http://139.28.223.9:3000; # Или ваше доменное имя

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
